# Generated by Django 6.0.6 on 2026-06-14 19:09

import resumes.schema
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='My Resume', help_text="A human-readable label for this resume (e.g., 'Software Engineer Resume').", max_length=255)),
                ('template_id', models.CharField(default='classic', help_text='The visual template to use when rendering this resume.', max_length=50)),
                ('document_data', models.JSONField(default=resumes.schema.get_empty_resume_document, help_text='Full §6.2-compliant JSON Resume document. Validated on API write.')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Django session key of the browser that created this resume.', max_length=40)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
