# Generated by Django 5.0.6 on 2026-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ai_credits',
            field=models.IntegerField(default=30),
        ),
    ]
